### ISSUE TITLE
maxPoolSize doesn't seem to have any effect

### ISSUE THREAD

**Issue by lygoing** [vert-x3/vertx-redis-client#224] opened 2020-04-18 15:25 UTC
### Questions

I used 1 and 1000 for performance testing, but the throughput I got was the same. So I suspect maxPoolSize has no effect.

I'm not sure this is a bug, I'm still learning vertx.

### Version

Redis server: 5.0.8
Vert.x core: 3.9.0
vertx-redis-client: 3.9.0

### Context

I tried local services and cloud services, and the test results are the same.

### Do you have a reproducer?

[https://github.com/lygoing/redis-benchmark](https://github.com/lygoing/redis-benchmark)

### Steps to reproduce

1. Configuration file application-test.yml
2. run test `RedisTest.put()`
3. run test `RedisTest.doGetBenchmark()`

**Comment by pmlopes** [comment] 2020-04-20 14:19
Seems to be a duplicate of #220

**Comment by pmlopes** [comment] 2020-04-20 14:19
The related issue has been fixed on master, the algorithm was wrong and only allowing 4 connections regardless of the config.

**Closed by pmlopes** 2020-04-20 14:19 UTC
Labels: duplicate

**Comment by lygoing** [comment] 2020-04-20 14:28
@pmlopes  Thanks  🍮
