### ISSUE TITLE
Redis connection pool leaks when handling exceptions.

### ISSUE THREAD

**Issue by zhoudingyun** [vert-x3/vertx-redis-client#267] opened 2020-11-30 13:53 UTC
### Version
Vert.x > 4.0.0

 RedisAPI.api(redis).get("test").onSuccess(a->{
           // todo something   #If there is an exception here, it will cause the connection pool to leak. 
        }).onFailure(t->{
           
        });

**Comment by pmlopes** [comment] 2020-12-01 11:02
@zhoudingyun can you provide an example of this showing the leak? I'm looking at the code and I already see:

```
try {
  ...
} finally {
  conn.close()
}
```

To ensure this issue doesn't happen. The fix is on `CR2`.

**Comment by zhoudingyun** [comment] 2020-12-01 11:10
@pmlopes 
example:
RedisAPI.api(redis).get("test").onSuccess(a->{
 int a = 1;
 int b = 0;
 int c = a/b;
}).onFailure(t->{

 });

**Comment by zhoudingyun** [comment] 2020-12-01 11:10
@pmlopes
example:
RedisAPI.api(redis).get("test").onSuccess(ar->{
    int a = 1;
    int b = 0;
    int c = a/b;
}).onFailure(t->{

});

**Comment by pmlopes** [comment] 2020-12-01 15:24
Sorry @zhoudingyun I cannot reproduce the issue. I've created the test:

```java
  @Test
  public void simpleTest2(TestContext should) {
    final Async test = should.async();


    final Redis client = Redis.createClient(rule.vertx(), "redis://localhost:7006");

    client
      .send(Request.cmd(Command.PING), send -> {
        System.out.println(client);
        int a = 1;
        int b = 0;
        int c = a/b;
        test.complete();
      });

    rule.vertx().setTimer(5000L, t -> {
      System.out.println(client);
    });
  }
```

And on the `BaseRedisClient` I've print the connection, this is the output:

```
io.vertx.redis.client.impl.RedisStandaloneConnection@238cc03c
io.vertx.redis.client.impl.RedisClient@3eca348
Dec 01, 2020 4:20:55 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
java.lang.ArithmeticException: / by zero
...
io.vertx.redis.client.impl.RedisClient@3eca348
```

So on the second call the redis connection is not leaked, it's reused. Note that `close()` does not immediately closes the connection, as it may be reused (because it's a connection pool).

**Comment by zhoudingyun** [comment] 2020-12-01 15:35
public class TestApplication {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();
        final Redis redis = Redis.createClient(vertx, "redis://172.18.20.76:6379");

        vertx.setPeriodic(1000, aa->{
            RedisAPI.api(redis).get("aa").onSuccess(ar -> {
                int a = 1;
                int b = 0;
                int c = a / b;
            }).onFailure(t -> {
                System.out.println(t.getMessage());
            });
        });

    }
}
![image](https://user-images.githubusercontent.com/32148584/100761390-d06e6300-342d-11eb-908e-5fb932d0f0f5.png)
![image](https://user-images.githubusercontent.com/32148584/100761406-d5cbad80-342d-11eb-9c96-ed2bc2744f7d.png)

**Comment by pmlopes** [comment] 2020-12-01 15:49
Thanks! I'll try to rewrite the test to use your approach and investigate!

**Comment by pmlopes** [comment] 2020-12-02 09:10
I've run your example with the current `master` and on my linux box it only uses a few connections if I leave it to run for a very long period:

```
~ $ netstat -ano|grep 7006
tcp        0      0 172.17.0.1:34770        172.17.0.2:7006         ESTABLISHED off (0.00/0/0)
tcp6       0      0 :::7006                 :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 127.0.0.1:40178         127.0.0.1:7006          ESTABLISHED keepalive (7108,00/0/0)
tcp6       0      0 127.0.0.1:7006          127.0.0.1:40178         ESTABLISHED keepalive (12,83/0/0)
```

I'm guessing it could be related how connections are handled on Windows?

**Comment by vietj** [comment] 2021-01-12 13:25
can we close this issue @pmlopes ?

**Comment by pmlopes** [comment] 2021-01-13 19:07
I'll close the issue as I can't reproduce it. Please reopen if more info is available.

**Closed by pmlopes** 2021-01-13 19:08 UTC
Labels: help wanted, wontfix
