### ISSUE TITLE
Redis client handler is not being called.

### ISSUE THREAD

**Issue by zeref1993** [vert-x3/vertx-redis-client#64] opened 2016-09-08 13:28 UTC
### Version
- vert.x core:3.3.2
- vert.x redis client:3.3.2
### Context

Hi,
 We are calling the following code in execute blocking in event loop
redisClient.setex(demandFactorRedisKeyPrefix + key, keyExpiry, value, r -> {
log.info("inside handler");
}

We have 8 verticles and redisclient is a static variable shared across all verticle instances. Redisclient is initialized by passing one of the vertx instances.
We are noticing that sometimes the handler is not called. 

Can you please help us in debugging the issue.

**Comment by pmlopes** [comment] 2016-09-15 07:51
In order to debug we need a reproducer example.

**Comment by pmlopes** [comment] 2017-01-18 09:50
Since there is no reproducer to allow testing this issue, I'll close it until more info is available.

**Closed by pmlopes** 2017-01-18 09:50 UTC
Labels: help wanted, invalid
