### ISSUE TITLE
io.vertx.core.impl.NoStackTraceThrowable: Redis connection is broken

### ISSUE THREAD

**Issue by dingaiminGIT** [vert-x3/vertx-redis-client#177] opened 2019-08-08 02:41 UTC
### Version

* vert.x core:3.8.0
* vert.x redis client:3.8.0

### Context

redisComponent.readableDSPRedis().get(redisKey, ar -> {
                timerContext.stop();
                if (ar.failed()) {
                    ar.cause().printStackTrace();
                    handler.handle(Future.failedFuture(new SearchException("getAdNum 异常, redis key " + redisKey)));
               ......
            });

public class RedisComponent {
    private ThreadLocal<RedisPool> readableDSPRedisPool = new ThreadLocal<>();
    private Vertx vertx = Application.vertx();
    private class RedisPool {
        private String name;
        private RedisClient[] redisClients;
        private final AtomicInteger idx = new AtomicInteger();
        public RedisPool(String configKey, int num) {
            this.name = configKey;
            String config = ConfigUtils.getString(configKey);
            String[] items = config.split(":");
            redisClients = new RedisClient[num];
            for (int i = 0; i < num; i++) {
                RedisOptions redisOptions = new RedisOptions();
                redisOptions.setConnectTimeout(1000);
                redisOptions.setReceiveBufferSize(8192);
                redisOptions.setSendBufferSize(8192);
                redisOptions.setReconnectAttempts(60);
                redisOptions.setReconnectInterval(1000);
                redisOptions.setTcpKeepAlive(true);
                redisOptions.setTcpNoDelay(true);
                redisOptions.setHost(items[0]);
                redisOptions.setPort(Integer.parseInt(items[1]));
                redisOptions.setMetricsName(configKey);
                if (items.length == 3 && StringUtils.isNotBlank(items[2])) {
                    redisOptions.setAuth(items[2]);
                }
                RedisClient redisClient = RedisClient.create(vertx, redisOptions);
                redisClients[i] = redisClient;
            }
        }

        public RedisClient get() {
            return redisClients[Math.abs(idx.getAndIncrement() % redisClients.length)];
        }

        public String getName() {
            return name;
        }
    }

    public RedisClient readableDSPRedis() {
        RedisPool redisPool = readableDSPRedisPool.get();
        if (redisPool == null) {
            redisPool = new RedisPool("redis.dsp.s", 3);
            readableDSPRedisPool.set(redisPool);
        }
        return redisPool.get();
    }
}

when request becomes more,then comes exception: io.vertx.core.impl.NoStackTraceThrowable: Redis connection is broken

i can trace the code at io.vertx.redis.client.impl.RedisClient#send line 243

**Comment by myhtls** [comment] 2019-08-12 08:15
Hi I also have the same problem as you.
  val options = RedisOptions()
        options.password = "you password"
        options.po
        val reids = Redis.createClient(vertx,options)
        val redisApi = RedisAPI.api(reids)
        redisApi.setnx("===","=====aaaa") {
            if(it.succeeded()){
                println("11")
            }else {
                println(it.failed())
                it.cause().printStackTrace()
            }
        }

it.failed false

**Comment by guss77** [comment] 2019-09-15 13:41
I still get this error (`io.vertx.core.impl.NoStackTraceThrowable: Redis connection`) in Vert.x Redis 3.8.1, even though issues #148 and #152 are closed.

Reviewing the code of `RedisClientImpl` from 3.8.1, I don't see anywhere that a reconnect is handled.

Currently, my workaround is to detect "connection is broken" errors by searching the text message of the exception thrown (horrible way to do that), then calling `RedisClient#close()` and re-running the request. `close()` is atomic so we shouldn't need to wait for it to complete and should be safe to be called synchronously.

I wish `send()` would handle that internally.

**Comment by Tinadim** [comment] 2019-09-26 13:38
I'm having the same issue. Looks like in version 4.0.0 the code that handles the socket connection has been changed greatly. Is version 4 stable yet?

**Comment by pablotdl** [comment] 2019-10-03 20:48
Same issue here, solved using the workaround applied by @guss77 , but definitely not ideal

**Comment by romero** [comment] 2019-12-05 10:44
Still there in 3.8.4 =)

**Comment by rvega-arg** [comment] 2019-12-11 12:47
I can confirm still there in 3.8.4

**Comment by edouardswiac** [comment] 2019-12-21 04:49
Same here.

**Comment by pmlopes** [comment] 2019-12-21 09:28
Can you try out the current master? The new API supports connection pooling out of the box and does connection management for you.

**Comment by vietj** [comment] 2020-01-13 09:23
@pmlopes can we backport the new connection pool to 3.8 ?

**Comment by pmlopes** [comment] 2020-01-16 08:44
I've been looking at it, but I'm afraid the code change is enourmous and will require almost a full rewrite to the old API. The reason is that the 2 branches have diverged a lot and master is using promises and a new connection interface that is not compatible with the 3.x way of things.

Otherwise look at the docs where an example of implement re-connect is part of the examples until you can safely upgrade to the 4.x releases.

**Comment by barbarosalp** [comment] 2020-02-09 15:12
I think this is the reason for "the try reconnect example does not work"?

**Comment by abdullahwaqar** [comment] 2020-03-22 10:59
Can confirm that issue still persists.

**Comment by pmlopes** [comment] 2020-03-23 19:11
@barbarosalp and @abdullahwaqar many updates have been added to the 3.9 branch, have you tried that one? or which version are you using?

Please note that with 3.9 the new client API that will be default on 4.0 is also backported, so we can phase out the old one. (it's a transition version, so we expect that users start upgrading as all old APIs are marked as deprecated).

**Comment by abdullahwaqar** [comment] 2020-03-24 10:30
No, i think i was trying to work with 3.8, added the dependency using vertex starter so it came with 3.8 i guess.

**Comment by LoranceChen** [comment] 2020-04-09 16:24
3.9.0 is out now!at a glance of the source code which RedisClusterConnection will give a retry(16 times) on send method. And the error message "redis connection is broken" is removed form 3.9.0.

Does someone test the bug is fixed in 3.9.0?

**Comment by rvega-arg** [comment] 2020-04-11 15:59
I moved one of my services with this issue to 3.9.0 5 days ago. It is working without issues since then.

**Comment by LoranceChen** [comment] 2020-04-16 14:21
I have test 3.9.0 but sorry for it not works for cluster mode.   
`redis.connect` give a callback with success result which means endpoint could be connected and password is ok. but both of RedisAPI and redis.send use command result with a failure: `ErrorType: NOAUTH Authentication required.`   
Besides, another error occurred when I manually send a AUTH command. The error is `RedisClusterClient does not handle command auth,use non cluster client on the right node.`  

Is it a bug?  
Thanks.

**Comment by pmlopes** [comment] 2020-04-24 19:58
@LoranceChen the auth issue is related to #222

**Comment by pmlopes** [comment] 2020-10-06 11:04
auth has been fixed on master, we now cover all auth modes, resp2 and resp3.

I'll close this issue for now and if anything is missing, please create a new issue for the specific problem.

**Closed by pmlopes** 2020-10-06 11:04 UTC
