### ISSUE TITLE
Redis do not restore contextual data

### ISSUE THREAD

**Issue by glassfox** [vert-x3/vertx-redis-client#254] opened 2020-10-13 13:47 UTC
Hi,
Any data stored in context, disappear after redis command.

vertx-redis-client.4.0.0-beta3

Following the test that reproduce the issue.

```
import java.util.Objects;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import io.vertx.core.AbstractVerticle;
import io.vertx.core.Vertx;
import io.vertx.core.impl.ContextInternal;
import io.vertx.core.logging.Log4j2LogDelegateFactory;
import io.vertx.junit5.Timeout;
import io.vertx.junit5.VertxExtension;
import io.vertx.junit5.VertxTestContext;
import io.vertx.redis.client.Redis;
import io.vertx.redis.client.RedisAPI;
import io.vertx.redis.client.RedisOptions;

@ExtendWith(VertxExtension.class)
@Timeout(10000)
public class RedisClientTest {
	static{
		System.setProperty("vertx.logger-delegate-factory-class-name",
				Log4j2LogDelegateFactory.class.getName());	
	}
	
	private static final String CONTEXTUAL_KEY = "val";
	
	private static Logger logger = LogManager.getLogger(RedisClientTest.class);
	
	private RedisAPI redisApi;
	private Redis redis;
	
	@BeforeEach
	void setUp(Vertx vertx, VertxTestContext context) throws Exception {
		
		var options = new RedisOptions();
		options.setConnectionString("redis://localhost:6379").setMaxWaitingHandlers(10);
		
		redis = Redis.createClient(vertx, options);
		redisApi = RedisAPI.api(redis);
		context.completeNow();
	}

	@AfterEach
	void tearDown() throws Exception {
		redis.close();
	}

	@Test
	void test(Vertx vertx, VertxTestContext ctx) {
		logger.debug("test");
		vertx.deployVerticle(new AbstractVerticle() {
			@Override
			public void start() throws Exception {
				var expected = UUID.randomUUID().toString();
				logger.trace("contextual value:{}", expected);
				put(CONTEXTUAL_KEY, expected);
				redisApi.get("some_redis_key")
				.map(res -> {
					var actual = get(CONTEXTUAL_KEY);
					Assertions.assertEquals(expected, actual);
					return null;
				}).onComplete(ctx.succeedingThenComplete());
			}
		});
	}
	
	private static String put(String key, String value) {
		Objects.requireNonNull(key);
		Objects.requireNonNull(value);
		ContextInternal ctx = (ContextInternal) Vertx.currentContext();
		if (ctx == null) {
			if (logger.isTraceEnabled()) {
				logger.trace("Attempt to set contextual data from a non Vert.x thread");
			}
			return null;
		} else {
			return contextualDataMap(ctx).put(key, value);
		}
	}

	public static String get(String key) {
		Objects.requireNonNull(key);
		ContextInternal ctx = (ContextInternal) Vertx.currentContext();
		if (ctx != null) {
			return contextualDataMap(ctx).get(key);
		}
		return null;
	}
	
	private static ConcurrentMap<String, String> contextualDataMap(ContextInternal ctx) {
		Objects.requireNonNull(ctx);
		return (ConcurrentMap<String, String>) ctx.localContextData().computeIfAbsent(RedisClientTest.class, k -> new ConcurrentHashMap<String,String>());
	}
}
```

**Comment by pmlopes** [comment] 2020-10-20 07:51
@glassfox could you give a try with the current `master` ? I've fixed a bug with right context/thread that may solve your issue.

**Comment by pmlopes** [comment] 2020-10-20 07:52
Maybe a duplicate of #256

**Comment by glassfox** [comment] 2020-10-22 08:19
Thanks @pmlopes.
Looks good.

**Comment by glassfox** [comment] 2020-11-05 11:15
@pmlopes Just to ensure. The actual fix do not included in CR1.

**Comment by pmlopes** [comment] 2021-03-12 10:30
We do have thread checking tests ATM, will close for now. If the issue still persists, please reopen.

**Closed by pmlopes** 2021-03-12 10:30 UTC
Labels: bug
